name: README Otomatik Güncelle

on:
  push:
    branches:
      - main  # veya kendi ana branşın
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Gerekli modülleri yükle
        run: pip install requests

      - name: README.md dosyasını güncelle
        run: python generate-projects-table.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🧠 README proje tablosu otomatik güncellendi" || echo "No changes to commit"
          git push
